kind: pipeline
type: docker
name: build

steps:
- name: cooked
  image: ilhamxm/image:latest
  environment:
    token:
      from_secret: bot_api
  commands:
  - wget https://raw.githubusercontent.com/IlhamXM/Scripts/master/kernel/CI/vince/drone49
  - bash drone49
